<a href="https://colab.research.google.com/github/GonzaOrtiz85/APRENDIZAJE_AUTOMATICO_2026/blob/main/Semana1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Ejercicio 1
Crear un array de 10 elementos con ceros:





In [3]:
array_ceros = np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 2
Generar un array con los números del 1 al 20

In [4]:
array_1_20 = np.arange(1, 21)
print(array_1_20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Ejercicio 3
Crear un array con los números pares del 2 al 50

In [5]:
array_pares = np.arange(2, 51, 2)
print(array_pares)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Ejercicio 5
Crear una matriz de 4x4 con valores aleatorios entre 0 y 1

In [6]:
matriz_aleatoria = np.random.rand(4, 4)
print(matriz_aleatoria)

[[0.19434717 0.80073032 0.07186317 0.73464423]
 [0.35610865 0.16839024 0.70449157 0.4318504 ]
 [0.35109338 0.93921204 0.17392364 0.0826025 ]
 [0.5009033  0.53744858 0.40636298 0.07331296]]


Ejercicio 6
Suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6]

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


Ejercicio 7
Multiplicar dos matrices 3x3 de enteros aleatorios entre 1 y 10

In [8]:
matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

resultado = np.dot(matriz1, matriz2)

print("Matriz 1:")
print(matriz1)

print("Matriz 2:")
print(matriz2)

print("Multiplicación:")
print(resultado)

Matriz 1:
[[ 9  3  8]
 [ 7  3 10]
 [ 5  7  9]]
Matriz 2:
[[ 1  6  5]
 [ 3  9  9]
 [ 7 10 10]]
Multiplicación:
[[ 74 161 152]
 [ 86 169 162]
 [ 89 183 178]]


Ejercicio 8
Crear un array de 15 valores aleatorios entre 1 y 100 e imprimir máximo, mínimo y promedio

In [9]:
array_random = np.random.randint(1, 101, 15)

print("Array:")
print(array_random)

print("Máximo:", np.max(array_random))
print("Mínimo:", np.min(array_random))
print("Promedio:", np.mean(array_random))

Array:
[80  4 50 78 32 74 46 49 48 86 36 27 66 49 68]
Máximo: 86
Mínimo: 4
Promedio: 52.86666666666667


Ejercicio 9
Generar una matriz 5x5 con valores del 1 al 25 y extraer su diagonal

In [10]:
matriz_1_25 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_1_25)

print("Matriz:")
print(matriz_1_25)

print("Diagonal:")
print(diagonal)

Matriz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal:
[ 1  7 13 19 25]


Ejercicio 10
Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcular la suma de cada fila y columna

In [11]:
matriz_random = np.random.randint(1, 21, (5, 5))

suma_filas = np.sum(matriz_random, axis=1)
suma_columnas = np.sum(matriz_random, axis=0)

print("Matriz:")
print(matriz_random)

print("Suma de cada fila:")
print(suma_filas)

print("Suma de cada columna:")
print(suma_columnas)

Matriz:
[[16  8 14  4  6]
 [12  1 18 16  1]
 [ 8 18  6 18 16]
 [13 17 17  1  2]
 [ 2 10 10  8 19]]
Suma de cada fila:
[48 48 66 50 49]
Suma de cada columna:
[51 54 65 47 44]


**En esta primera semana trabajé con NumPy para crear arrays y matrices, y hacer operaciones básicas como suma, búsqueda de máximos y mínimos, promedio, diagonales y suma por filas y columnas.**

**Estos ejercicios me ayudaron a entender mejor cómo manejar datos numéricos en Python de una forma más ordenada y rápida. También pude ver la diferencia entre un array y una matriz, y cómo NumPy simplifica mucho este tipo de tareas.**